parameters:
#    centro_log.example.class: Gestor_cocina\CentroLogBundle\Example

services:
#    centro_log.example:
#        class: %centro_log.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
