# recetas:
#     resource: "@RecetasBundle/Resources/config/routing.yml"
#     prefix:   /

# almacen:
#     resource: "@AlmacenBundle/Resources/config/routing.yml"
#     prefix:   /

# centro_log:
#     resource: "@CentroLogBundle/Resources/config/routing.yml"
#     prefix:   /
inicio:
    pattern: /inicio
    defaults: { _controller: RecetasBundle:Default:index }
    # -----------------------------------------------------------
recetas:
    pattern: /recetas
    defaults: { _controller: RecetasBundle:Default:recetas }
nueva_receta:
    pattern: /recetas/nueva_receta
    defaults: { _controller: RecetasBundle:Default:nueva_receta }
crear_receta:
    pattern: /recetas/nueva_receta/crear
    defaults: { _controller: RecetasBundle:FormRecetas:crear_receta }
listar_ing:
    pattern: /recetas/nueva_receta/crear/listar_ing
    defaults: { _controller: AlmacenBundle:Default:listarProductos }
# -------------------------------------------------------------------------#
centro_log:
    pattern: /centro_log
    defaults: { _controller: CentroLogBundle:Default:index }
almacen:
    pattern: /almacen
    defaults: { _controller: AlmacenBundle:Default:index }
nuevo_producto:
    pattern: /almacen/nuevo_producto
    defaults: { _controller: AlmacenBundle:Default:nuevo_producto }

perfil:
    pattern: /perfil
    defaults: { _controller: RecetasBundle:User:index }

