# recetas:
#     resource: "@RecetasBundle/Resources/config/routing.yml"
#     prefix:   /

# almacen:
#     resource: "@AlmacenBundle/Resources/config/routing.yml"
#     prefix:   /

# centro_log:
#     resource: "@CentroLogBundle/Resources/config/routing.yml"
#     prefix:   /
inicio:
    pattern: /
    defaults: { _controller: RecetasBundle:Default:index }
buscar:
    pattern: /buscar
    defaults: { _controller: RecetasBundle:Default:buscar }

  # -----------------------------------------------------------#
registro:
    pattern: /registro
    defaults: { _controller:RecetasBundle:User:registro }
crear_usuario:
    pattern: /crear_usuario
    defaults: { _controller:RecetasBundle:User:crear_usuario }
perfil:
    pattern: /perfil
    defaults: { _controller: RecetasBundle:User:perfil }
edit_usuario:
    pattern: /edit_usuario/{usuario}
    defaults: { _controller: RecetasBundle:User:editPerfil }
borrarUsuario:
    pattern: /borrarUsuario
    defaults: { _controller: RecetasBundle:User:borrarUsuario }
editarRol:
    pattern: /editarRol
    defaults: { _controller: RecetasBundle:User:editarRol }    
  # -----------------------------------------------------------#
login:
    pattern: /login
    defaults: { _controller:RecetasBundle:Security:login }
login_check:
    pattern: /login_check
logout:
    pattern: /logout
    # -----------------------------------------------------------#
upload_file:
    pattern: /upload_file
    defaults: { _controller:RecetasBundle:Default:upload_file }
upload:
    pattern: /upload
    defaults: { _controller:RecetasBundle:Default:upload }
# -----------------------------------------------------------#
receta:
    pattern: /receta/{receta}
    defaults: { _controller: RecetasBundle:Default:receta }
recetas:
    pattern: /recetas
    defaults: { _controller: RecetasBundle:Default:recetas }
getrecetas:
    pattern: /getrecetas
    defaults: { _controller: RecetasBundle:Default:getRecetas }

filtro_cat:
    pattern: /recetas/filtrar/{categoria}
    defaults: { _controller: RecetasBundle:Default:filtrar }
nueva_receta:
    pattern: /recetas/nueva_receta
    defaults: { _controller: RecetasBundle:Default:nueva_receta }
crear_receta:
    pattern: /recetas/nueva_receta/crear
    defaults: { _controller: RecetasBundle:FormRecetas:crear_receta }

listar_ing:
    pattern: /recetas/nueva_receta/crear/listar_ing
    defaults: { _controller: AlmacenBundle:Default:listarProductos }
editar_receta:
    pattern: /recetas/editar/{receta}
    defaults: { _controller: RecetasBundle:Default:editar_receta }
mod_receta:
    pattern: /recetas/editar/mod/{receta}
    defaults: { _controller: RecetasBundle:FormRecetas:editar_receta }
borrar_receta:
    pattern: /recetas/borrar/{receta}
    defaults: { _controller: RecetasBundle:Default:borrar_receta }
# -------------------------------------------------------------------------#
nueva_categoria:
    pattern: /recetas/nueva_categoria
    defaults: { _controller: RecetasBundle:FormRecetas:nueva_categoria }
edit_categoria:
    pattern: /recetas/edit_categoria
    defaults: { _controller: RecetasBundle:FormRecetas:edit_categoria }
del_categoria:
    pattern: /recetas/del_categoria
    defaults: { _controller: RecetasBundle:FormRecetas:del_categoria }
# -------------------------------------------------------------------------#
valorar:
    pattern: /recetas/valorar
    defaults: { _controller: RecetasBundle:Default:valorar }

# -------------------------------------------------------------------------#
solicitudes:
    pattern: /solicitudes
    defaults: { _controller: CentroLogBundle:Default:solicitudes }
pedir_productos:
    pattern: /solicitudes/pedir_productos
    defaults: { _controller: CentroLogBundle:Default:pedir_productos }
prodSolicitado:
    pattern: /solicitudes/prodSolicitado
    defaults: { _controller: CentroLogBundle:Default:prodSolicitado }
# prodSolicitado:
#     pattern:/solicitudes/prodSolicitado
#     defaults: { _controller: CentroLogBundle:Default:prodSolicitado }
# -------------------------------------------------------------------------#
centro_log:
    pattern: /centro_log
    defaults: { _controller: CentroLogBundle:Default:index }
genSolicitud:
    pattern: /recetas/genSolicitud
    defaults: { _controller: CentroLogBundle:Default:genSolicitud }
delSolicitud:
    pattern: /recetas/delSolicitud
    defaults: { _controller: CentroLogBundle:Default:delSolicitud }
genPedido:
    pattern: /centro_log/genPedido
    defaults: { _controller: CentroLogBundle:Default:genPedido }
findPedido:
    pattern: /centro_log/findPedido
    defaults: { _controller: CentroLogBundle:Default:findPedido }
editPedido:
    pattern: /centro_log/editPedido
    defaults: { _controller: CentroLogBundle:Default:editPedido }
delPedido:
    pattern: /centro_log/delPedido
    defaults: { _controller: CentroLogBundle:Default:delPedido }
editEstado:
    pattern: /centro_log/editEstado
    defaults: { _controller: CentroLogBundle:Default:editEstado }
validarPedido:
    pattern: /centro_log/validarPedido
    defaults: { _controller: CentroLogBundle:Default:validarPedido }
# -------------------------------------------------------------------------#
almacen:
    pattern: /almacen
    defaults: { _controller: AlmacenBundle:Default:index }
getProd:
    pattern: /almacen/getProd
    defaults: { _controller: AlmacenBundle:Default:getProd }
nuevo_producto:
    pattern: /almacen/nuevo_producto
    defaults: { _controller: AlmacenBundle:Default:nuevo_producto }
mod_producto:
    pattern: /almacen/mod_producto/{producto}
    defaults: { _controller: AlmacenBundle:Default:mod_producto }
getproductos:
    pattern: /almacen/getproductos
    defaults: { _controller: AlmacenBundle:Default:getProductos }
crear_producto:
    pattern: /almacen/nuevo_producto/crear
    defaults: { _controller: AlmacenBundle:FormProductos:crear_producto }
editar_producto:
    pattern: /almacen/nuevo_producto/editar/{producto}
    defaults: { _controller: AlmacenBundle:FormProductos:editar_producto }
borrar_producto:
    pattern: /almacen/borrar_producto/{producto}
    defaults: { _controller: AlmacenBundle:FormProductos:borrar_producto }

verproductos:
    pattern: /verproductos
    defaults: {_controller: RecetasBundle:Default:verProductos }
# -------------------------------------------------------------------------#








# fp_openid_security:
#     resource: "@FpOpenIdBundle/Resources/config/routing/security.xml"