security:
    encoders:
        Gestor_cocina\RecetasBundle\Entity\Usuarios: plaintext
        # Gestor_cocina\RecetasBundle\Entity\Usuarios:        { algorithm: sha512, iterations: 10 }
            # algorithm: sha512
            # encode-as-base64: true
            # iterations: 10
 
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_USER]
 
    providers:
        user_db:
            entity: { class: Gestor_cocina\RecetasBundle\Entity\Usuarios, property: username }
 
    firewalls:
        main:
            pattern: /.*
            provider: user_db
            form_login:
                login_path: /login
                check_path: /login_check
                # remember_me: true
            logout:
                path: /logout
                target: /
                invalidate_session: false
            # remember_me:
            #     key: MiClaveSegura
            #     lifetime: 1800
            #     path: /.*
            #     domain: ~
            security: true
            anonymous: true
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /recetas, roles: ROLE_USER }
        - { path: /solicitudes, roles: ROLE_USER }
        - { path: /centro_log, roles: ROLE_ADMIN }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
