<?php

namespace Gestor_cocina\CentroLogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Ped_ProdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Ped_ProdRepository extends EntityRepository
{
}
