<?php

namespace Gestor_cocina\CentroLogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SolicitudProdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudProdRepository extends EntityRepository
{
}
