<?php

namespace Proxies\__CG__\Gestor_cocina\AlmacenBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Productos extends \Gestor_cocina\AlmacenBundle\Entity\Productos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Gestor_cocina\\AlmacenBundle\\Entity\\Productos' . "\0" . 'id', '' . "\0" . 'Gestor_cocina\\AlmacenBundle\\Entity\\Productos' . "\0" . 'nombre', '' . "\0" . 'Gestor_cocina\\AlmacenBundle\\Entity\\Productos' . "\0" . 'slug', '' . "\0" . 'Gestor_cocina\\AlmacenBundle\\Entity\\Productos' . "\0" . 'precio', '' . "\0" . 'Gestor_cocina\\AlmacenBundle\\Entity\\Productos' . "\0" . 'unidadCompra', '' . "\0" . 'Gestor_cocina\\AlmacenBundle\\Entity\\Productos' . "\0" . 'unidad', '' . "\0" . 'Gestor_cocina\\AlmacenBundle\\Entity\\Productos' . "\0" . 'stock', '' . "\0" . 'Gestor_cocina\\AlmacenBundle\\Entity\\Productos' . "\0" . 'stockMin', '' . "\0" . 'Gestor_cocina\\AlmacenBundle\\Entity\\Productos' . "\0" . 'foto');
        }

        return array('__isInitialized__', '' . "\0" . 'Gestor_cocina\\AlmacenBundle\\Entity\\Productos' . "\0" . 'id', '' . "\0" . 'Gestor_cocina\\AlmacenBundle\\Entity\\Productos' . "\0" . 'nombre', '' . "\0" . 'Gestor_cocina\\AlmacenBundle\\Entity\\Productos' . "\0" . 'slug', '' . "\0" . 'Gestor_cocina\\AlmacenBundle\\Entity\\Productos' . "\0" . 'precio', '' . "\0" . 'Gestor_cocina\\AlmacenBundle\\Entity\\Productos' . "\0" . 'unidadCompra', '' . "\0" . 'Gestor_cocina\\AlmacenBundle\\Entity\\Productos' . "\0" . 'unidad', '' . "\0" . 'Gestor_cocina\\AlmacenBundle\\Entity\\Productos' . "\0" . 'stock', '' . "\0" . 'Gestor_cocina\\AlmacenBundle\\Entity\\Productos' . "\0" . 'stockMin', '' . "\0" . 'Gestor_cocina\\AlmacenBundle\\Entity\\Productos' . "\0" . 'foto');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Productos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', array($slug));

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', array());

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecio($precio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecio', array($precio));

        return parent::setPrecio($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecio', array());

        return parent::getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidadCompra($unidadCompra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidadCompra', array($unidadCompra));

        return parent::setUnidadCompra($unidadCompra);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidadCompra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidadCompra', array());

        return parent::getUnidadCompra();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidad($unidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidad', array($unidad));

        return parent::setUnidad($unidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidad', array());

        return parent::getUnidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setStock($stock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStock', array($stock));

        return parent::setStock($stock);
    }

    /**
     * {@inheritDoc}
     */
    public function getStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStock', array());

        return parent::getStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setStockMin($stockMin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStockMin', array($stockMin));

        return parent::setStockMin($stockMin);
    }

    /**
     * {@inheritDoc}
     */
    public function getStockMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockMin', array());

        return parent::getStockMin();
    }

    /**
     * {@inheritDoc}
     */
    public function setFoto($foto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoto', array($foto));

        return parent::setFoto($foto);
    }

    /**
     * {@inheritDoc}
     */
    public function getFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoto', array());

        return parent::getFoto();
    }

}
