parameters:
#    almacen.example.class: Gestor_cocina\AlmacenBundle\Example

services:
#    almacen.example:
#        class: %almacen.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
